### Create config
POST http://localhost/api/config
Content-Type: application/json

{
  "name": "logging_dev",
  "value": "1"
}

### Check create config validation
POST http://localhost/api/config
Content-Type: application/json

{

}
