### Create config
POST http://localhost/api/config
Content-Type: application/json
X-AUTH-TOKEN: 123

{
  "name": "logging_dev1",
  "value": "33"
}

### Check create config validation
POST http://localhost/api/config
Content-Type: application/json

{

}

###Get config list
GET http://localhost/api/config/list
Content-Type: application/json
X-AUTH-TOKEN: 123
