### Show User
POST http://localhost/api/user/3
Content-Type: application/json
X-AUTH-TOKEN: 123

###
POST http://localhost/api/user/1/calculate-access
Content-Type: application/json
X-AUTH-TOKEN: 123


### Add location
PUT http://localhost/api/user/1/location/1
Content-Type: application/json
X-AUTH-TOKEN: 123

### Find user
GET http://localhost/api/user/find/Simtel
Content-Type: application/json
X-AUTH-TOKEN: 123

### Get users by location
GET http://localhost/api/users/{location-id}
Content-Type: application/json
X-AUTH-TOKEN: 123

### Find user
GET http://localhost/_profiler/
X-AUTH-TOKEN: 123
